SUMMARY = "SleekXMPP is an elegant Python library for XMPP (aka Jabber, Google Talk, etc)."
DESCRIPTION = "SleekXMPP is an MIT licensed XMPP library for Python 2.6/3.1+"
HOMEPAGE = "http://github.com/fritzy/SleekXMPP"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=793ed5ae033c57a8ea15e2748f0762e5"

SRC_URI[md5sum] = "92f51b09378e7ff74874f4914a8a1018"
SRC_URI[sha256sum] = "d213c1de71d92505f95ced0460ee0f84fdc4ddcacb7d7dd343739ed4028e5569"

PYPI_PACKAGE = "sleekxmpp"

